server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: media
          uri: lb://msvc-media
          predicates:
            - Path=/api/v1/media/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
