server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: msvc-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka