server:
  port: 9090

spring:
  application:
    name: msvc-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

msvc:
  api:
    url: localhost:8080

application:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # a week
